TRUNCATE TABLE post CASCADE;
TRUNCATE TABLE privatemessage CASCADE;
TRUNCATE TABLE section CASCADE;
TRUNCATE TABLE thread CASCADE;
TRUNCATE TABLE threadfollowers CASCADE;
TRUNCATE TABLE "user" CASCADE;